# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitsDatePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True, db_index=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShortenURL',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('shortened_id', models.BigIntegerField(default=0)),
                ('short_url', models.CharField(default='', max_length=10)),
                ('hits', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLVisits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('url_id_fk',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='URL_Shortner.ShortenURL')),
            ],
        ),
        migrations.AddField(
            model_name='hitsdatepoint',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='URL_Shortner.ShortenURL'),
        ),
        migrations.AlterUniqueTogether(
            name='hitsdatepoint',
            unique_together=set([('day', 'link')]),
        ),
    ]
