# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('URL_Shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlvisits',
            name='browser',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='urlvisits',
            name='device',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='urlvisits',
            name='platform',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
